# Generated by Django 5.2.5 on 2025-09-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_posts"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="caption",
            field=models.CharField(default=""),
        ),
    ]
