# Generated by Django 5.2.5 on 2025-09-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_posts_caption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="pic",
            field=models.ImageField(
                blank=True,
                default="defaults/defaultProfile.png",
                null=True,
                upload_to="profile_pics/",
            ),
        ),
    ]
