# Generated by Django 5.2.5 on 2025-09-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0025_alter_application_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="description",
            field=models.CharField(max_length=2000),
        ),
    ]
